"""Measurements table

Revision ID: 0356fedf35a6
Revises: 9105277514d5
Create Date: 2020-12-03 13:10:37.892002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0356fedf35a6'
down_revision = '9105277514d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waist', sa.Float(precision=10), nullable=True),
    sa.Column('hips', sa.Float(precision=10), nullable=True),
    sa.Column('bust', sa.Float(precision=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    # ### end Alembic commands ###
